#!/bin/sh
# commit-msg hook for Conventional Commits Minimal
# https://github.com/nakat-t/conventional-commits-minimal
#
# Usage:
#   commit-msg.sh <path-to-commit-message-file>   (git commit-msg hook)
#   commit-msg.sh < message.txt                    (read message from stdin)
#
# Exit status: 0 when the message conforms (or is a Git-generated message that
# is intentionally skipped), 1 when it violates the specification.
#
# POSIX sh only. Requires: cat, tr, sed, grep, printf.

# --- read the message ------------------------------------------------------
if [ "$#" -ge 1 ]; then
  if [ ! -r "$1" ]; then
    printf 'commit-msg: cannot read %s\n' "$1" >&2
    exit 1
  fi
  raw=$(cat "$1")
else
  raw=$(cat)
fi

# --- normalize -------------------------------------------------------------
# * drop CR so CRLF files behave like LF files
# * drop everything from the scissors line onwards (git commit --verbose)
# * drop comment lines (default core.commentChar is '#')
cleaned=$(printf '%s\n' "$raw" \
  | tr -d '\r' \
  | sed -e '/^# -\{1,\} >8 -\{1,\}$/,$d' -e '/^#/d')

# remove leading blank lines
cleaned=$(printf '%s\n' "$cleaned" | sed -e '/./,$!d')

header=$(printf '%s\n' "$cleaned" | sed -n '1p')
rest=$(printf '%s\n' "$cleaned" | sed -e '1d')

# an empty message is rejected by git itself; nothing for us to say
if [ -z "$header" ]; then
  exit 0
fi

# --- skip messages generated by git ----------------------------------------
case "$header" in
  "Merge "*|"Revert \""*|"fixup! "*|"squash! "*|"amend! "*)
    exit 0
    ;;
esac

# --- helpers ---------------------------------------------------------------
fail() {
  printf 'commit-msg: %s\n' "$1" >&2
  printf '\n  %s\n\n' "$header" >&2
  printf 'Expected format (Conventional Commits Minimal):\n\n' >&2
  printf '  <type>[!]: <description>\n\n' >&2
  printf '  <type> is one of: feat, fix, chore (lowercase)\n' >&2
  printf '  !      marks a breaking change\n' >&2
  printf '  scope  is not allowed\n' >&2
  exit 1
}

matches() {
  printf '%s\n' "$1" | grep -Eq -- "$2"
}

# --- validate the header ---------------------------------------------------
if ! matches "$header" '^(feat|fix|chore)!?: [^[:space:]]'; then
  if matches "$header" '^[A-Za-z]+(\([^)]*\))'; then
    fail 'scope is not allowed; use "<type>: <description>" or "<type>!: <description>"'
  fi
  if matches "$header" '^[Ff][Ee][Aa][Tt]([!:]|$)' \
     || matches "$header" '^[Ff][Ii][Xx]([!:]|$)' \
     || matches "$header" '^[Cc][Hh][Oo][Rr][Ee]([!:]|$)'; then
    if ! matches "$header" '^(feat|fix|chore)'; then
      fail 'type must be lowercase (feat, fix, chore)'
    fi
  fi
  if matches "$header" '^(feat|fix|chore)!?:[[:space:]]*$'; then
    fail 'description must not be empty'
  fi
  if matches "$header" '^(feat|fix|chore)!?:[^[:space:]]'; then
    fail 'a single space is required after the colon'
  fi
  if matches "$header" '^(feat|fix|chore)!?[[:space:]]'; then
    fail 'a colon is required immediately after the type (and "!" if present)'
  fi
  if matches "$header" '^(feat|fix|chore)!?[^!:]'; then
    fail 'unknown type; allowed types are feat, fix, chore'
  fi
  if matches "$header" '^[A-Za-z][A-Za-z0-9_-]*!?:'; then
    fail 'unknown type; allowed types are feat, fix, chore'
  fi
  fail 'header does not match "<type>[!]: <description>"'
fi

# --- validate the body separator -------------------------------------------
if [ -n "$rest" ]; then
  second=$(printf '%s\n' "$rest" | sed -n '1p')
  if [ -n "$second" ]; then
    fail 'body must be separated from the description by exactly one blank line'
  fi
fi

# --- validate BREAKING CHANGE footers --------------------------------------
if matches "$rest" '^[Bb][Rr][Ee][Aa][Kk][Ii][Nn][Gg][ -][Cc][Hh][Aa][Nn][Gg][Ee](: | #)'; then
  if ! matches "$rest" '^BREAKING[ -]CHANGE(: | #)'; then
    fail 'the BREAKING CHANGE footer token must be uppercase'
  fi
  if ! matches "$header" '^(feat|fix|chore)!:'; then
    fail 'a BREAKING CHANGE footer requires "!" after the type (e.g. "feat!: ...")'
  fi
fi

exit 0
