# commit-msg hook for Conventional Commits Minimal
# https://github.com/nakat-t/conventional-commits-minimal
#
# Usage:
#   commit-msg.ps1 <path-to-commit-message-file>   (git commit-msg hook)
#   Get-Content message.txt | commit-msg.ps1        (read message from stdin)
#
# Exit status: 0 when the message conforms (or is a Git-generated message that
# is intentionally skipped), 1 when it violates the specification.
#
# Compatible with Windows PowerShell 5.1 and PowerShell 7+.

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$Path,

    [Parameter(ValueFromPipeline = $true)]
    [string[]]$InputObject
)

begin {
    $stdinLines = New-Object System.Collections.Generic.List[string]
}

process {
    if ($null -ne $InputObject) {
        foreach ($line in $InputObject) { $stdinLines.Add($line) }
    }
}

end {
    $ErrorActionPreference = 'Stop'

    # --- read the message ------------------------------------------------
    if ($Path) {
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
            [Console]::Error.WriteLine("commit-msg: cannot read $Path")
            exit 1
        }
        $raw = [System.IO.File]::ReadAllText($Path)
    }
    elseif ($stdinLines.Count -gt 0) {
        $raw = ($stdinLines -join "`n")
    }
    else {
        $raw = [Console]::In.ReadToEnd()
    }

    # --- normalize -------------------------------------------------------
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($line in ($raw -replace "`r", '') -split "`n") {
        if ($line -match '^# -+ >8 -+$') { break }   # scissors line
        if ($line -match '^#') { continue }          # comment line
        $lines.Add($line)
    }
    while ($lines.Count -gt 0 -and $lines[0] -eq '') { $lines.RemoveAt(0) }

    # an empty message is rejected by git itself; nothing for us to say
    if ($lines.Count -eq 0) { exit 0 }

    $header = $lines[0]
    $rest = @()
    if ($lines.Count -gt 1) { $rest = @($lines.GetRange(1, $lines.Count - 1)) }

    # --- skip messages generated by git ----------------------------------
    if ($header -match '^(Merge |Revert "|fixup! |squash! |amend! )') { exit 0 }

    # --- helpers ---------------------------------------------------------
    function Fail([string]$Reason) {
        $err = [Console]::Error
        $err.WriteLine("commit-msg: $Reason")
        $err.WriteLine('')
        $err.WriteLine("  $header")
        $err.WriteLine('')
        $err.WriteLine('Expected format (Conventional Commits Minimal):')
        $err.WriteLine('')
        $err.WriteLine('  <type>[!]: <description>')
        $err.WriteLine('')
        $err.WriteLine('  <type> is one of: feat, fix, chore (lowercase)')
        $err.WriteLine('  !      marks a breaking change')
        $err.WriteLine('  scope  is not allowed')
        exit 1
    }

    # --- validate the header ---------------------------------------------
    # -cmatch is case-sensitive; -match is case-insensitive.
    if ($header -cnotmatch '^(feat|fix|chore)!?: \S') {
        if ($header -cmatch '^[A-Za-z]+\([^)]*\)') {
            Fail 'scope is not allowed; use "<type>: <description>" or "<type>!: <description>"'
        }
        if ($header -match '^(feat|fix|chore)([!:]|$)' -and $header -cnotmatch '^(feat|fix|chore)') {
            Fail 'type must be lowercase (feat, fix, chore)'
        }
        if ($header -cmatch '^(feat|fix|chore)!?:\s*$') {
            Fail 'description must not be empty'
        }
        if ($header -cmatch '^(feat|fix|chore)!?:\S') {
            Fail 'a single space is required after the colon'
        }
        if ($header -cmatch '^(feat|fix|chore)!?\s') {
            Fail 'a colon is required immediately after the type (and "!" if present)'
        }
        if ($header -cmatch '^(feat|fix|chore)!?[^!:]') {
            Fail 'unknown type; allowed types are feat, fix, chore'
        }
        if ($header -cmatch '^[A-Za-z][A-Za-z0-9_-]*!?:') {
            Fail 'unknown type; allowed types are feat, fix, chore'
        }
        Fail 'header does not match "<type>[!]: <description>"'
    }

    # --- validate the body separator -------------------------------------
    if ($rest.Count -gt 0 -and $rest[0] -ne '') {
        Fail 'body must be separated from the description by exactly one blank line'
    }

    # --- validate BREAKING CHANGE footers --------------------------------
    $breakingLines = @($rest | Where-Object { $_ -match '^BREAKING[ -]CHANGE(: | #)' })
    if ($breakingLines.Count -gt 0) {
        $uppercase = @($breakingLines | Where-Object { $_ -cmatch '^BREAKING[ -]CHANGE(: | #)' })
        if ($uppercase.Count -ne $breakingLines.Count) {
            Fail 'the BREAKING CHANGE footer token must be uppercase'
        }
        if ($header -cnotmatch '^(feat|fix|chore)!:') {
            Fail 'a BREAKING CHANGE footer requires "!" after the type (e.g. "feat!: ...")'
        }
    }

    exit 0
}
